version: "2"
linters:
  enable:
    - dogsled
    - err113
    - exhaustive
    - gocritic
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - promlinter
    - revive
    - unconvert
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
    revive:
      rules:
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - err113
          - errcheck
          - funlen
          - gochecknoglobals
          - gosec
          - noctx
          - revive
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
